/**
 * Equifax Integration Mock Data
 * Security features and WebView URLs
 */

import {EquifaxSecurityFeature} from '../types/equifax';

/**
 * Equifax security feature configurations
 * In production, these URLs would come from backend API for secure authentication
 */
export const equifaxSecurityFeatures: EquifaxSecurityFeature[] = [
  {
    type: 'freeze',
    title: 'Manage Credit Freeze',
    description: 'Freeze or unfreeze your Equifax credit file to prevent unauthorized access.',
    icon: 'lock-closed',
    color: '#007AFF',
    url: 'https://www.equifax.com/personal/credit-report-services/credit-freeze/',
    requiresAuth: true,
  },
  {
    type: 'fraud-alert',
    title: 'Add Fraud or Active Duty Alert',
    description: 'Place fraud or active duty military alerts on your credit report.',
    icon: 'shield-checkmark',
    color: '#FF9500',
    url: 'https://www.equifax.com/personal/credit-report-services/credit-fraud-alerts/',
    requiresAuth: true,
  },
  {
    type: 'dispute',
    title: 'Submit a Dispute',
    description: 'Dispute inaccurate information on your Equifax credit report.',
    icon: 'create',
    color: '#34C759',
    url: 'https://www.equifax.com/personal/credit-report-services/credit-dispute/',
    requiresAuth: true,
  },
];

/**
 * Feature details and help text
 */
export const equifaxFeatureDetails = {
  freeze: {
    title: 'Credit Freeze',
    benefits: [
      'Prevents new creditors from accessing your credit report',
      'Helps protect against identity theft',
      'Free to freeze and unfreeze',
      'Does not affect your credit score',
    ],
    considerations: [
      'You must unfreeze before applying for new credit',
      'Separate freeze required for each bureau (Equifax, Experian, TransUnion)',
      'May take up to 24 hours to process freeze/unfreeze',
    ],
    howToUse: [
      'Tap "Manage Credit Freeze" to open Equifax website',
      'Log in to your Equifax account',
      'Follow prompts to freeze or unfreeze your credit',
      'Save your PIN for future access',
    ],
  },
  'fraud-alert': {
    title: 'Fraud & Active Duty Alerts',
    benefits: [
      'Initial fraud alert lasts 1 year',
      'Extended fraud alert (identity theft victim) lasts 7 years',
      'Active duty alert lasts 1 year (renewable)',
      'Creditors must verify identity before opening new accounts',
    ],
    considerations: [
      'Only need to place alert with one bureau (automatically shared)',
      'May slow down credit applications',
      'Does not prevent access to your credit report',
    ],
    howToUse: [
      'Tap "Add Fraud or Active Duty Alert"',
      'Log in to your Equifax account',
      'Select alert type (Fraud or Active Duty)',
      'Provide required documentation if needed',
      'Submit alert request',
    ],
  },
  dispute: {
    title: 'Submit a Dispute',
    benefits: [
      'Correct inaccurate information on your credit report',
      'Free dispute process',
      'Investigation typically completed within 30 days',
      'Can improve your credit score if dispute is successful',
    ],
    considerations: [
      'Gather supporting documentation before filing',
      'Be specific about what information is incorrect',
      'Bureau has 30 days to investigate',
      'Not all disputes result in changes',
    ],
    howToUse: [
      'Tap "Submit a Dispute" to open Equifax',
      'Log in to your account',
      'Select the item you want to dispute',
      'Explain why the information is inaccurate',
      'Upload supporting documents',
      'Submit and track your dispute',
    ],
  },
};

/**
 * Mock authenticated URLs (in production, these would be generated by backend)
 * These include auth tokens and return URLs for deep linking back to the app
 */
export const getMockEquifaxAuthenticatedUrl = (
  featureType: 'freeze' | 'fraud-alert' | 'dispute',
  userId: string,
): string => {
  const baseUrls = {
    freeze:
      'https://www.equifax.com/personal/credit-report-services/credit-freeze/',
    'fraud-alert':
      'https://www.equifax.com/personal/credit-report-services/credit-fraud-alerts/',
    dispute:
      'https://www.equifax.com/personal/credit-report-services/credit-dispute/',
  };

  // In production, backend would append authentication tokens and return URLs
  // Example: `${baseUrl}?token=${authToken}&return_url=${encodeURIComponent('creditguard://equifax-complete')}`
  return baseUrls[featureType];
};

/**
 * WebView allowed domains for security
 */
export const equifaxAllowedDomains = [
  'equifax.com',
  'www.equifax.com',
  'my.equifax.com',
  'assets.equifax.com',
];

/**
 * Mock WebView success detection
 * In production, this would be based on URL patterns or postMessage events
 */
export const isEquifaxActionComplete = (url: string): boolean => {
  // Example success URL patterns
  const successPatterns = [
    '/freeze/complete',
    '/fraud-alert/complete',
    '/dispute/submitted',
    '/success',
    '/confirmation',
  ];

  return successPatterns.some((pattern) => url.includes(pattern));
};

/**
 * Help text for WebView screen
 */
export const equifaxWebViewHelpText = {
  loading: 'Loading Equifax...',
  error: 'Unable to load Equifax. Please check your internet connection.',
  security:
    'You are securely connected to Equifax.com. Your login credentials are managed directly by Equifax.',
  returnToApp: 'Complete your action on Equifax, then return to CreditGuard.',
};
